# Generated by Django 3.2.21 on 2023-10-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20231018_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='portfolio_url',
        ),
    ]
