# Generated by Django 3.2.21 on 2023-10-01 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('category', models.CharField(choices=[('Conference', 'Conference'), ('Networking', 'Networking'), ('Panel', 'Panel'), ('Product launch', 'Product launch'), ('Talk', 'Talk'), ('Workshop', 'Workshop'), ('Other', 'Other')], default='Conference', max_length=50)),
                ('format', models.CharField(choices=[('In person', 'In person'), ('Hybrid', 'Hybrid'), ('Online', 'Online')], default='In person', max_length=50)),
                ('image', models.ImageField(blank=True, default='../default_post_e675n6', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
