# Generated by Django 3.2.21 on 2023-10-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='../default_post_e675n6', upload_to='images/'),
        ),
    ]
